RBLD_ARCHIVES := xcompmgr-1.1.6.tar.gz
RBLD_WORKSRC := xcompmgr-1.1.6
RBLD_CONFCMD := ./autogen.sh

RBLD_FETCH_URI[xcompmgr-1.1.6.tar.gz] := http://cgit.freedesktop.org/xorg/app/xcompmgr/snapshot/xcompmgr-1.1.6.tar.gz

include ../../template.mk
